package com.mx.mr.job;
//PENDIENTES
//BASE DE DATOS
//1 CREAR CADA SECUENCIA PARA CADA TABLA
//2 INGRESAR DATOS A LAS TABLAS

//CODIGO
//1 EN LA CLASE JUGADOR UTIL CREAR LOS METODOS NECESARIOS PARA VALIDAR LOS DISTINTOS TIPOS DE DATOS
//2 TODOS LOS ID DE TODOS LOS DTO DEBEN SER LONG
//3 INSTALAR POSTMAN

public class SportPlayApp {

}
